
  root = "."
  tmp_dir = "tmp"

  [build]
    bin = "./tmp/main"
    cmd = "go build -o ./tmp/main ."
    delay = 1000
    exclude_dir = ["tmp", "vendor"]
    include_ext = ["go", "tpl", "tmpl", "html"]
    stop_on_error = true

  [log]
    time = true

  [color]
    main = "magenta"
    watcher = "cyan"
    build = "yellow"
    runner = "green"
