services:
  app:
    build: .
    command: air -c .air.toml
    environment:
      GO_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      # DB_USER: ${DB_USER}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_NAME: ${DB_NAME}
    env_file:
      - path: .env
        required: false
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/home/apiUser/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-go_careers}
      MYSQL_USER: ${DB_USER:-apiuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed_data/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql_data:
